# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(898, 542)
        # MainWindow.setTabShape(QtCore.Qt.QTabWidget::TabShape::Rounded)
        # MainWindow.setDockOptions(QtCore.Qt.QMainWindow::DockOption::AllowTabbedDocks|QtCore.Qt.QMainWindow::DockOption::AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.controls_tab = QtWidgets.QWidget()
        self.controls_tab.setObjectName("controls_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.controls_tab)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.text_input_1 = QtWidgets.QLineEdit(self.controls_tab)
        self.text_input_1.setObjectName("text_input_1")
        self.verticalLayout_2.addWidget(self.text_input_1)
        self.enter_button = QtWidgets.QPushButton(self.controls_tab)
        self.enter_button.setObjectName("enter_button")
        self.verticalLayout_2.addWidget(self.enter_button)
        self.start_button = QtWidgets.QPushButton(self.controls_tab)
        self.start_button.setObjectName("start_button")
        self.verticalLayout_2.addWidget(self.start_button)
        self.stop_button = QtWidgets.QPushButton(self.controls_tab)
        self.stop_button.setObjectName("stop_button")
        self.verticalLayout_2.addWidget(self.stop_button)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.graphics_view = QtWidgets.QGraphicsView(self.controls_tab)
        self.graphics_view.setObjectName("graphics_view")
        self.horizontalLayout.addWidget(self.graphics_view)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.tabWidget.addTab(self.controls_tab, "")
        self.settings_tab = QtWidgets.QWidget()
        self.settings_tab.setObjectName("settings_tab")
        self.tabWidget.addTab(self.settings_tab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.enter_button.setText(_translate("MainWindow", "Enter"))
        self.start_button.setText(_translate("MainWindow", "Start"))
        self.stop_button.setText(_translate("MainWindow", "Stop"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.controls_tab), _translate("MainWindow", "Controls"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings_tab), _translate("MainWindow", "Settings"))
