# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from app import Ui_MainWindow 
import functions
import database
import datetime

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)

    controller = functions.Controller()
    database_connection = database.Database("localhost", "root", "", "plc_data_1")

    ## Connect the buttons ##############################
    # user_input = ui.text_input.text()
    
    # ui.enter_button.clicked.connect(controller.send_message)
    ui.enter_button.clicked.connect(lambda: controller.send_message(int(ui.text_input_1.text())))
    ui.enter_button.clicked.connect(lambda: database_connection.insert_data(int(ui.text_input_1.text()),datetime.datetime.now()))
    ui.start_button.clicked.connect(lambda: controller.turn_light(True))
    ui.stop_button.clicked.connect(lambda:  controller.turn_light(False))


    #####################################################

    MainWindow.show()
    sys.exit(app.exec_())
