# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

## Third party
from PyQt5 import QtCore, QtGui, QtWidgets
import datetime

import functions
import database
from app import Ui_MainWindow 
import ui_editor;

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui_editor.edit_ui(ui)

    MainWindow.setWindowIcon(QtGui.QIcon('A://StoredData/test/python-interface/controlx-logo.png'))
    MainWindow.setWindowTitle("ControlX GUI")

    

    controller = functions.Controller()
    database_connection = database.Database("localhost", "plc_login", "test123", "plc_data_1")

    ## Connect the buttons ##############################
    # user_input = ui.text_input.text()
    
    # ui.enter_button.clicked.connect(controller.send_message)
    ui.enter_button.clicked.connect(lambda: controller.send_message(int(ui.text_input_1.text())))
    ui.enter_button.clicked.connect(lambda: database_connection.insert_data(int(ui.text_input_1.text()),datetime.datetime.now()))
    ui.start_button.clicked.connect(lambda: controller.turn_light(True))
    ui.stop_button.clicked.connect(lambda:  controller.turn_light(False))
    #####################################################
    ui.plot_widget_1.plot([1,2,3,4,5], [30,35,30,35,30], pen='r')
    ######################################################


    MainWindow.show()
    sys.exit(app.exec_())
